### ISSUE TITLE
How to use in android gradle3.0

### ISSUE THREAD

**Issue by xyhm520** [gmazzo/gradle-buildconfig-plugin#1]
dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
         classpath "com.github.gmazzo:gradle-buildconfig-plugin:1.3.3"
    }
apply plugin: "com.github.gmazzo.buildconfig" ???????

**Comment by gmazzo** [comment]
Android has built-in support for buildConfigField, you don't need this plugin:
https://developer.android.com/studio/build/gradle-tips
