### ISSUE TITLE
buildconfig plugin breaks "parallel" gradle builds

### ISSUE THREAD

**Issue by eekboom** [gmazzo/gradle-buildconfig-plugin#10]
Tested on Windows 10 20H2:

- Clone this project: https://github.com/bnorm/kotlin-ir-plugin-template
- Execute `.\gradlew build -Dorg.gradle.parallel=false -Dorg.gradle.configureondemand=false --no-build-cache`
- => build works fine
- To cleanup execute `.\gradlew clean`, `.\gradlew --stop`, `rd /s /q .gradle`
- Execute `.\gradlew build -Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true --no-build-cache`
- => Bug: Build fails with `kotlin-ir-plugin-template\kotlin-ir-plugin-native\src\main\kotlin\com\bnorm\template\TemplateCommandLineProcessor.kt: (36, 35): Unresolved reference: BuildConfig`

**Comment by gmazzo** [comment]
Can you try `2.1.0`? I don't have a Windows machine, but I've fixed the integration with Gradle's build chain. It should work now

**Comment by eekboom** [comment]
Thanks a lot! Yes, now parallel build seems to work fine!
