### ISSUE TITLE
Upgrade to v5.0.0 and over causes Unresolved reference

### ISSUE THREAD

**Issue by dhakehurst** [gmazzo/gradle-buildconfig-plugin#157]
v4.2.0 works fine
anything 5.0.0 and above does not.

I cannot see anything in the release notes to explain my issue.

I get this error
```
import com.github.gmazzo.gradle.plugins.BuildConfigExtension
                                    ^ Unresolved reference: gradle
```
 
 example project where this is an issue
 [https://github.com/dhakehurst/kotlin.gradle.plugin.exportPublic]

**Comment by gmazzo** [comment]
Probably I misted on documenting the breaking change, but I've repackaged the classes under `com.github.gmazzo.buildconfig`.

You should replace the import to `com.github.gmazzo.buildconfig.BuildConfigExtension`

**Comment by gmazzo** [comment]
Nope, it has been documented indeed https://github.com/gmazzo/gradle-buildconfig-plugin/releases/tag/v5.0.0
> Plugin classes has been repackaged to `com.github.gmazzo.buildconfig`

**Comment by dhakehurst** [comment]
Thanks,
Sorry I missed the documentation of the change.

thanks for the quick response.
