### ISSUE TITLE
Can make buildConfigField for each platform

### ISSUE THREAD

**Issue by the-best-is-best** [gmazzo/gradle-buildconfig-plugin#188]
android {
      defaultConfig {
        ...
buildConfigField("String", "interstitialAd" , "ca-app-pub-7284367511062855/7574670867")
        buildConfigField("String", "bannerAd" , "ca-app-pub-7284367511062855/6312687941")

}
// for native android only

can do it for ios or any platform or not

**Comment by gmazzo** [comment]
You can, if you are using Kotlin Multiplaform and then apply this plugin. 

Please refer you the plugin documentation, as the DSL you have shared is from Android Gradle Plugin and not from this one

**Comment by the-best-is-best** [comment]
I don't understand I use kotlin multiplatform already but don't see the doc

**Comment by the-best-is-best** [comment]
not correct answer 
    sourceSets {

        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.kermit)
            implementation(libs.koin.core)
            implementation(libs.koin.compose)



            implementation(libs.voyager.navigator)
            implementation(libs.voyager.screenmodel)
            implementation(libs.voyager.koin)

            implementation(libs.compottie)
            implementation(libs.composesearchabledropdown)
            implementation(libs.kadmob)


            implementation(project(":core"))
            implementation(libs.compose.webview.multiplatform)

            implementation(compose.materialIconsExtended)
            implementation(libs.kyoutube)
            implementation(libs.compose.toast)

        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            @OptIn(ExperimentalComposeLibrary::class)
            implementation(compose.uiTest)
            implementation(libs.kotlinx.coroutines.test)
        }

        androidMain.dependencies {
            implementation(compose.uiTooling)
            implementation(libs.androidx.activityCompose)
            implementation(libs.kotlinx.coroutines.android)



        }
        iosMain.dependencies {

        }

    } my code

**Comment by the-best-is-best** [comment]
sourceSets {
        buildConfig {
            getByName("android")
            buildConfigField("String", "interstitialAd" , "\"")
            buildConfigField("String", "bannerAd" , "\"")

            getByName("ios"){

                buildConfigField("String", "interstitialAd" , "\"")
                buildConfigField("String", "bannerAd" , "\"")

            }
        }
        commonMain.dependencies { }
   androidMain.dependencies {}
 iosMain.dependencies {}
   getByName("android") ??    getByName("ios") how add this names and how it work any full example why readme not tell me how use it

**Comment by the-best-is-best** [comment]
if this correct


buildConfig {
    // BuildConfig configuration here.
    // https://github.com/gmazzo/gradle-buildconfig-plugin#usage-in-kts

    buildConfigField("String", "PRIVACY_URL", "\"http://michelleacademy.getenjoyment.net/two_square_game/privacy_policy/privacy_policy.html\"")

    sourceSets {
        getByName("android") {
            buildConfigField(
                "String",
                "interstitialAd",
                "\"ca-app-pub-7284367511062855/7574670867\""
            )
            buildConfigField("String", "bannerAd", "\"ca-app-pub-7284367511062855/6312687941\"")
        }
        getByName("ios") {

            buildConfigField(
                "String",
                "interstitialAd",
                "\"ca-app-pub-7284367511062855/1974850970\""
            )
            buildConfigField("String", "bannerAd", "\"ca-app-pub-7284367511062855/9759925938\"")

        }
    }

}
 how fix DefaultBuildConfigSourceSet with name 'android' not found.

**Comment by gmazzo** [comment]
Initialize KMP before the `buildConfig` block or use `maybeCreate` instead

**Comment by the-best-is-best** [comment]
It is working now and I use compose Multiplatform so I make expect class for this
