### ISSUE TITLE
Delete the output directory at the beginning if the generateBuildConfig task is executed

### ISSUE THREAD

**Issue by ahasbini** [gmazzo/gradle-buildconfig-plugin#2]
When changing the `packageName` in the `buildConfig` and making a build, I noticed the output directory with the old `packageName` being left behind and was compiled as well. To prevent this from happening, the output directory should be deleted in case the inputs (and maybe outputs?) of the `generateBuildConfig` task were changed and the task had to be executed.

**Comment by gmazzo** [comment]
Thanks! Fixed at https://github.com/gmazzo/gradle-buildconfig-plugin/commit/cd461cec5b0f82cde05fc974fefd01375a14975b#diff-0e9d31c19d8611a1cb265a07ea1fae3aR110 and released as `1.6.2` ;)
