### ISSUE TITLE
[kotlin] Support nullable types

### ISSUE THREAD

**Issue by felixdivo** [gmazzo/gradle-buildconfig-plugin#21]
Supporting setting null values would be neat for something like the following (and probably be reasonably easy to implement):

```kotlin
if (debug)
    buildConfigField("java.nio.file.Path?", "SOME_KEY", "\"value\"")
else
    buildConfigField("java.nio.file.Path?", "SOME_KEY", "null")
```

But a line `import java.nio.file.Path?` is generated, which will not compile.

**Proposal** (I don't know the library internals): Modify `buildConfigField(...)` to allow a `?` at the end of types (this is already the case) and remove it for the import statement. Additionally, to simplify the build config, one could map `value=null` to `"null"`, which would allow for the following code:

```kotlin
val maybeString: String? = if (something) null else "a real value"
buildConfigField("String?", "SOME_KEY", maybeString)
```

**Comment by gmazzo** [comment]
I think we can make the Kotlin generator smarter to property identify `?` as nullable, yes. Actually, I'm not convinced at all about how the field types are propagated to the generators. I originally ported the logic from AGP's but maybe it's time to consider a more robust DSL.

I'm not actively maintaining this repo, but feel free to open a PR.
