### ISSUE TITLE
Adding undefined fields to BuildConfig 

### ISSUE THREAD

**Issue by CodeRedDev** [gmazzo/gradle-buildconfig-plugin#22]
I'm currently trying to add a field to `BuildConfig` that depends on a Gradle project property that will be defined on some extra task.

Unfortunately I can't add my logic to the `buildConfig` extension as this will be executed at compile time and not on runtime if I understand that right. So my way is to add an extra task like this:

```kts
val generateBuildConfig by tasks
task("buildConfigToken") {
    val bConfig = buildConfig.forClass("BuildConfig")

    doFirst {
        println("BuildConfig: Token input!")

        val token =
            if (project.hasProperty("bot_token")) {
                project.property("bot_token")
            } else {
                "RELESE"
            }

        bConfig.buildConfigField("String", "BOT_TOKEN", "\"$token\"")
    }

    generateBuildConfig.dependsOn(this)
}
```

This leads to a second `BuildConfig` class in an extra source set.

Is there a way to add fields to the original `BuildConfig`?

**Comment by CodeRedDev** [comment]
Well I just came to realise that the `buildConfig` variable where I call `forClass()` represents the one for the original `BuildConfig` class. So I got my intended behaviour.

For me the only questions now would be if I am right about that the `buildConfig` extension block will be executed at compile time and not at runtime?

**Comment by gmazzo** [comment]
And remember you can always use the `Provider` syntax:
```kotlin
 buildConfigField("String", "APP_VERSION", provider { "\"${project.version}\"" })
 ```
