### ISSUE TITLE
When useKotlinOutput is used import of Boolean is wrong

### ISSUE THREAD

**Issue by ultraon** [gmazzo/gradle-buildconfig-plugin#25]
Hello, thank you for the library, it works great!

I noticed one minor issue, It would be great to cover it as a note on the library description page.
When I use `useKotlinOutput()` and `Boolean` type for `buildConfigField` I have to use `kotlin.Boolean` type instead.

Gradle error output:
```
e: /Users/my_user/my_project/build/generated/source/buildConfig/main/main/my/package/BuildConfig.kt: (3, 8): Unresolved reference: Boolean
```

Example of workaround:
```Kotlin
buildConfig {
    className("BuildConfig")
    packageName("my.package")
    useKotlinOutput()

    // buildConfigField("Boolean", "IS_MY_BOOLEAN", "true") // It isn't compiled
    buildConfigField("kotlin.Boolean", "IS_MY_BOOLEAN", "true") // It works well
}
```

**Comment by gmazzo** [comment]
This is "per-design" on Kotlinpet, so the "right" usage will be to use `kotlin.Boolean` or `boolean`
> KotlinPoet doesn't honor default imports. ClassName.bestGuess("IntArray") is synonymous with ClassName("", "IntArray") and so that test looks valid and correct from KotlinPoet's perspective despite being semantically incorrect from Kotlin's.

https://github.com/square/kotlinpoet/issues/645#issuecomment-471663982
