### ISSUE TITLE
Field visibilty support

### ISSUE THREAD

**Issue by Savrov** [gmazzo/gradle-buildconfig-plugin#27]
Afaik, the current version generates only "public" fields. So, if I have a module B, that depends on module A, and both of them have "configField" `NAME`, then I have access to both of them. It would be great to have a possibility to set field visibility, so module B has an internal `NAME`, and module A has an internal `NAME` as well

**Comment by gmazzo** [comment]
Adding this level of granularity it will be an overkill to me, considering that you can always create a second class with the `forClass(<name>)` DSL, that can have the desired visibility.

So, my advice on this will be to split your `BuildConfig` in two: one public/transitive and another private to the module.
