### ISSUE TITLE
Add Composable function generation from resource files

### ISSUE THREAD

**Issue by russellbanks** [gmazzo/gradle-buildconfig-plugin#29]
Currently, you can generate constants from the resource folder. However, in Jetpack/JetBrains Compose, to create a Painter object from a resource file you would need this:

```kotlin
@Composable
fun icon() = painterResource($path)
```

I am having to do this manually for all my images in my project so it would be useful if this could be generated.

**Comment by gmazzo** [comment]
Interesting feature, but I think it falls out of scope from this plugin originally mean to be a port of Android's `buildConfigField`.

Have you tried already writing your own Gradle task? It will be as easy as having a `FileCollection` as input, and per each file, generate a `@Composable fun` entry in a single `.kt` file. You can later bind the task with the `main` kotlin source set.

Something like this:
```kotlin
plugins {
       kotlin("jvm")
}

val composeRes = tasks.register("generateComposePainterResources") {
    val resources = fileTree(kotlin.sourceSets.main.map { it.resources }) {
        include("*.png", "*.jpg", "*.jpeg")
    }
    val outDir = layout.buildDirectory.dir("generated/compose-image-adapters")

    inputs.files(resources)
    outputs.dir(outDir)

    doFirst {
        val file = outDir.get().file("ComposeImages.kt").asFile

        file.writeText(resources.joinToString(
            separator = "\n\n", 
            prefix = "import androidx.compose.runtime.Composable\n\n"
        ) {
            """
                @Composable
                fun ${it.nameWithoutExtension}() = painterResource(${it.path})
            """.trimIndent()
        })
    }
}

kotlin.sourceSets.main.kotlin.source(composeRes)
```
