### ISSUE TITLE
Make the generated BuildConfig recognizable by the IDE

### ISSUE THREAD

**Issue by mr3y-the-programmer** [gmazzo/gradle-buildconfig-plugin#36]
Currently, when trying to use the plugin in a project, the generated `BuildConfig` object is inaccessible in code leading to IDE errors (e.g `Unresolved reference`) because the IDE isn't aware of its existence.
``` kotlin
BuildConfig.Foo // Unresolved reference
```
To make the IDE recognizes it, we need to treat the generated source dir the same as the project's main source directories.
it would be helpful to update the README to include this code snippet to avoid this annoying issue.
```kotlin
kotlin.sourceSets {
    main {
        kotlin.srcDirs(
            file("$buildDir/generated/source/buildConfig/main"),
        )
    }
}
```
PR #37 fixes this, and also add the equivalent code snippet for groovy `build.gradle` files.

**Comment by rocketraman** [comment]
In my Kotlin multi-platform project, I had to specify `$buildDir/generated/source/buildConfig/main` as the source dir.

**Comment by mr3y-the-programmer** [comment]
this also works for non multi-platform projects, I'll update the code snippet.

**Comment by jasonsparc** [comment]
I believe that a more correct solution is to hook into `prepareKotlinIdeaImport` task. See, https://twitter.com/Sellmair/status/1619308362881187840

**Comment by mr3y-the-programmer** [comment]
@jasonsparc I know about that tip, but I think you misunderstood the issue's main point here, that task would make `generateBuildConfig` run automatically on every gradle sync without having to do that manually yourself, but you still need a way to make the IDE aware of what you've just generated, and this is what the issue is addressing

**Comment by natros** [comment]
I'm not sure I understand the problem, but in all my projects the generated class is always visible and accessible to the IDE.

Am I missing something?

**Comment by jasonsparc** [comment]
@natros That's also what I thought.

The only time the generated classes won't be recognized by the IDE is when the various `generate*BuildConfig` tasks haven't run yet (that is, if they've *never* run yet). Also, as far as I know (or at least, last time I checked the plugin's source code), the generated directories are already under `kotlin.srcDirs`, since otherwise, the build won't recognize the newly generated source files. However, I could be wrong this time, or this issue might be for a different problem that I'm not getting.

**Comment by rocketraman** [comment]
@jasonsparc Thanks for the clarification. Digging a bit deeper, a plain vanilla gradle build works fine for me without the extra `srcDirs` declaration. And funnily enough, now so does the IDE, with no other changes or explicit source set declarations in my Gradle `buildConfig` configuration! So TBH, I have no idea why this didn't work for me before without that extra `srcDirs` declaration.

**Comment by mr3y-the-programmer** [comment]
@jasonsparc No, I'm not using the plugin in a multiplatform project, it is a relatively small android app with all the code in a single module `app`.

I'll create a minimal reproducible project, and I'll inform you

**Comment by mr3y-the-programmer** [comment]
@jasonsparc Here's a sample project: https://github.com/mr3y-the-programmer/build-config-bug.
it is a skeleton android app that has no plugins applied in the build script other than build config plugin alongside `com.android.application` & `org.jetbrains.kotlin.android` that applied to every android project.

**Steps to reproduce the issue:**

1. clone the project locally `git clone https://github.com/mr3y-the-programmer/build-config-bug.git`
2. Build the project using IDE or from the command line directly with `./gradlew build`

**Expected result:**
The build should fail from both IDE and the command line with the message `Unresolved reference: BuildConfig` due to calling BuildConfig in this line [MainActivity.kt#L29](https://github.com/mr3y-the-programmer/build-config-bug/blob/main/app/src/main/java/com/mr3y/ide_build_config_bug/MainActivity.kt#L29)

Now, Uncomment the workaround here at [build.gradle#L51](https://github.com/mr3y-the-programmer/build-config-bug/blob/main/app/build.gradle#L51), sync the project, and finally rerun build again from the IDE or from the command line, the build should complete successfully from both without any issues.

**Additional Context:**
Gradle version: 8.1.1
build config plugin version: 3.1.0 (latest version)
IDE: Android studio Flamingo that is based on Intellij IDEA 2022.2

**Comment by gmazzo** [comment]
Ok after reviewing this, I think the upcoming major release will also fix this. Basically, Android was never supported, because it has its own `BuildConfig` feature. 

The plugin was "working" in a detached way (no linked to any source set) because `kotlin-android` was not a recognized plugin. That's why you needed the extra `.srcDir`.

I'm introducing support in the upcoming major release.

**Comment by gmazzo** [comment]
This will be working on `4.0.0` version
