### ISSUE TITLE
[Ktor] Imports issue

### ISSUE THREAD

**Issue by yaroslav-android** [gmazzo/gradle-buildconfig-plugin#4]
### Problem description
I've trying to use your lib with [Ktor](https://ktor.io/) project. The issue that I faced is the import of files. 

IDEA cannot see `BuildConfig.TOKEN` 
![image](https://user-images.githubusercontent.com/46504259/71638147-c3b31f00-2c60-11ea-8bf9-1221dda951fa.png)

### Additional information

I've added it into `gradle.build` as ` buildConfigField("String", "TOKEN", "\"${token.app}\"")`. I am trying to call `BuildConfig.TOKEN` from `Application` class. 

I've checked generated class `BuildConfig` and it looks good:
```kotlin
package test.test.test.test

import kotlin.String

object BuildConfig {
    const val TOKEN: String =  "token"
}
```

**Comment by gmazzo** [comment]
Hey, can you provide a small sample project to test it? I'm not a Ktor user

**Comment by gmazzo** [comment]
Closing it for now, if you have a sample project I can test on, I'll take a look. Regards
