### ISSUE TITLE
KtLint does not like the generated code

### ISSUE THREAD

**Issue by ftomassetti** [gmazzo/gradle-buildconfig-plugin#55]
KtLint complain about the generated code:
```
> Task :ktlintMainSourceSetCheck FAILED
/Users/ftomassetti/repos/rpg-to-python-transpiler/build/generated/sources/buildConfig/main/com/strumenta/rpgle/BuildConfig.kt:6:1 Unexpected indentation (2) (should be 4) (indent)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ktlintMainSourceSetCheck'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /Users/ftomassetti/repos/rpg-to-python-transpiler/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
```

**Comment by ftomassetti** [comment]
This is the generated file:
```
package com.strumenta.rpgle

import kotlin.String

internal object BuildConfig {
  internal const val TRANSPILER_VERSION: String = "1.1.12"
}
```

**Comment by gmazzo** [comment]
Hi @ftomassetti, the style is the default of https://github.com/square/kotlinpoet. If there is any issue with ktLint codestyle, I think you should open it on that project.

Regardless of that, I think generated code should not be considered for code style check, only code that is under SCM should be, but that's opinionated of course.

**Comment by ftomassetti** [comment]
Thank you @gmazzo I have indeed excluded the code from being validated. However KtLint is more popular and used than Kotlin Poet, so probably Kotlin Poet should change and adapt, I think

**Comment by ftomassetti** [comment]
Anyway, thank you for your work. It is very useful! I will close the issue

**Comment by system1-dersek** [comment]
@ftomassetti out of curiosity, what pattern did you end up using to exclude the file?

Not sure if there's an easier approach than something like
```
    filter {
        exclude { entry ->
            entry.file.toString().contains("build/generated/")
        }
    }
```
the 'generated' part of the path is above the sources root that ktlint seems to use, so I wasn't able to make `**/generated/**` work.

**Comment by gmazzo** [comment]
>  what pattern did you end up using to exclude the file?

I didn't test myself, but based on the snippet you shared it may be get the list of generated dirs with:
```kotlin
val generatedDirs = mutableListOf<File>()

tasks.withType<BuildConfigTask>().configureEach {
    generatedDirs.add(outputDir.asFile.get())
}
```

**Comment by gmazzo** [comment]
> or even expose the builder in the implementation so that it can be modified before writeTo is called:
That could be some how a way to extend it, but it will not cover all cases. Codestyle is not just about indentation, but also line breaks, braces positioning, etc, etc.

Unless there is an easy standard way to link all together, like `.editorconfig` support from KotlinPoter (which I think it doesn't), I'd say this plugin is not a good fit for the use case.

At the end, you can still build the class yourself with an ad-hoc task.
