### ISSUE TITLE
New Gradle version mandates a JVM toolchain repository to be configured

### ISSUE THREAD

**Issue by jasonsparc** [gmazzo/gradle-buildconfig-plugin#59]
Cloning your repo then doing a `gradlew assemble` will give you the following error if the requested JVM toolchain hasn't been downloaded before:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':demo-project:generic'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':demo-project:generic:classpath'.
      > Failed to calculate the value of task ':plugin:compileJava' property 'javaCompiler'.
         > No matching toolchains found for requested specification: {languageVersion=8, vendor=any, implementation=vendor-specific}.
            > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).
```

Apparently, Gradle 8.X now mandates that a JVM toolchain download repository be configured. See the following Gradle docs:
- [Using automatic toolchain downloading without having a repository configured | Upgrading your build from Gradle 7.x to 8.0](https://docs.gradle.org/8.1.1/userguide/upgrading_version_7.html#using_automatic_toolchain_downloading_without_having_a_repository_configured)
- [Auto-provisioning | Toolchains for JVM projects](https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:provisioning)

---

The fix is actually quite simple, just prepend the following to both your `settings.gradle.kts` and `plugin/settings.gradle.kts`, then the build should succeed:

```kotlin
plugins {
    // For updates, see, https://github.com/gradle/foojay-toolchains
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
```

Now, I tried to add the code snippet above to your `gradle/shared.settings.gradle.kts` file but the build fails, since apparently, the `plugins` block isn't supported there (as it's applied as a [script plugin](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins)).

If you would like to explore the error above further and check that you've correctly applied the `foojay` plugin, simply delete the `jdk` directory in your [Gradle user home directory](https://docs.gradle.org/8.1.1/userguide/directory_layout.html#dir:gradle_user_home), then re-build your project.

P.S. I created this issue just in case it would be helpful if for example, people tried to build the project and the build fails due to Gradle's new toolchain repository requirement (and they don't know how to correctly resolve the issue). So I hope this would help anyone and everyone.

**Comment by jasonsparc** [comment]
I decided to quickly set up a PR (#60) in order to solve the above issue.

**Comment by gmazzo** [comment]
Thanks for reporting this and the PR. I'm having doubts about introducing this on an open-source project. The idea of using toolchain was to allow Gradle to automatically pick an installed JDK to build the project, but I'm a bit reluctant to introduce a plugin that may (unintentionally and untransparently) make local changes on whoever opens this project for the first time.

Opinionated, but I'd rather prefer to let the user choose which JDK to install and use to build this project. I think the error message is explicit enough to let them decide.

**Comment by jasonsparc** [comment]
Actually, the issue is not about having freedom in which JDK to use, but rather, your project currently requires two JDKs, one is JDK 8, set up by this [line](https://github.com/gmazzo/gradle-buildconfig-plugin/blob/v4.1.0/plugin/build.gradle.kts#L15), and the other is JDK 11, set up by this [line](https://github.com/gmazzo/gradle-buildconfig-plugin/blob/v4.1.0/demo-project/kts-android/build.gradle.kts#L9).

Because of that, Gradle's JVM toolchain requires that you have both JDK 8 and JDK 11 installed (in addition to your current JDK), or, just let Gradle download them for you. This was simpler in previous versions of Gradle (e.g., versions `7.X`), since the "download"-part was automatic: just declare which JVM toolchain to use and Gradle will download them for you. But then, the Gradle guys thought, it would be nice if you could customize that download logic, and hence, they decided to extract that part of Gradle into a separate plugin that you can now customize/replace, while also making sure that the users now declare a repository about where to download that custom download logic, thus introducing a change that might likely break builds for people that are unaware.

I like to think of that "toolchain download repository"-part as similar to how we could set up, e.g., which maven repository to use, or, should we use a custom maven repository in our Gradle builds (e.g., for corporate purposes), or something like that.

Not including the `foojay` thingy would therefore be like omitting the `mavenCentral()`, `google()`, and `gradlePluginPortal()` from your repository declarations. In fact applying that `org.gradle.toolchains.foojay-resolver-convention` plugin is similar to declaring the following:

```
plugins {
    id("org.gradle.toolchains.foojay-resolver") version "0.5.0"
}

toolchainManagement {
    jvm {
        javaRepositories {
            repository("foojay") {
                resolverClass.set(org.gradle.toolchains.foojay.FoojayToolchainResolver::class.java)
            }
        }
    }
}
```

…except that the above is more verbose.

Notice also that the above is similar to how repositories are declared under `pluginManagement.repositories` and `dependencyResolutionManagement.repositories`, but only uglier :P – so perhaps, that's why the Gradle people decided to ship `org.gradle.toolchains.foojay-resolver-convention` in addition to the `org.gradle.toolchains.foojay-resolver` plugin.

Now, I'm not sure why they don't want it to be automatic just like before: they could've just checked if `toolchainManagement.jvm.javaRepositories` is set or not, and then made the download logic automatic if not.

**Comment by jasonsparc** [comment]
Also, the JDK toolchains downloaded by Gradle are part of its cache (notice the `CACHEDIR.TAG` file in the `jdk` folder), just like the dependency artifacts that Gradle would otherwise download if not already downloaded. Those downloaded toolchains are meant to be used only by Gradle's build system and not externally, unlike an actual JDK installation. The `foojay` stuff is therefore like the `mavenCentral()` ritual that we often need to enact to make sure dependencies required by the build are downloaded if not already available.

**Comment by jasonsparc** [comment]
> but I'm a bit reluctant to introduce a plugin that may (unintentionally and untransparently) make local changes on whoever opens this project for the first time.

Ah! I see, so the confusion was that you thought the `foojay` plugin would change the user's local environment. That's not what the plugin does. Actually, what it's simply doing is restore the old behavior of Gradle (e.g., in versions `7.X`) in which the required toolchains are downloaded automatically in a hidden cache that Gradle manages (and may automatically be cleaned up by Gradle).

Think of it as something similar to, if Gradle didn't require the `mavenCentral()` ritual and everything works fine (dependencies are being downloaded automatically), then suddenly, a newer version of Gradle is released and now it requires that you declare that `mavenCentral()` ritual to tell Gradle that's where you really want to download your dependencies.

**Comment by gmazzo** [comment]
Ohh great then, can you iterate #60 to only apply the plugin on `plugin` module without the `includedBuild` refactor?

**Comment by jasonsparc** [comment]
You meant revert it back into a [script plugin](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins) and remove the included build, right?

I'm not sure if it's doable, since Gradle complains about the `plugins` block when placed in your `shared.settings.gradle.kts` script plugin, that's why I converted it into an included build. However, I think there's another way, I could apply the `foojay` plugin via the `apply(plugin = "...")` directive. So it might be doable with that instead.

I'll go ahead and try that, then I'll report to you my progress later.

**Comment by jasonsparc** [comment]
So I found out the reason why the `plugins` block can't be used in [script plugins](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins). Quote:

> The `plugins {}` block can currently only be used in a project’s build script and the `settings.gradle` file. It cannot be used in script plugins or init scripts.
>
> *Future versions of Gradle will remove this restriction.*
>
> If the restrictions of the `plugins {}` block are prohibitive, the recommended approach is to apply plugins using the [`buildscript {}` block](https://docs.gradle.org/current/userguide/plugins.html#sec:applying_plugins_buildscript).

From, https://docs.gradle.org/8.1.1/userguide/plugins.html#sec:build_scripts_only

---

Also, I tried to convert it into a script plugin (instead of the included build). The first issue I ran across was,

```
FAILURE: Build failed with an exception.

* What went wrong:
Plugin with id 'org.gradle.toolchains.foojay-resolver-convention' not found.
```

Contents of script plugin (first attempt):

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
    }
}

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("org.gradle.toolchains:foojay-resolver:0.5.0")
    }
}

apply(plugin = "org.gradle.toolchains.foojay-resolver-convention")
```

Second attempt:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
    plugins {
        id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
    }
}

apply(plugin = "org.gradle.toolchains.foojay-resolver-convention")
```

The second attempt results in the same error.

If however, we inline the contents of the shared script plugin among the `settings.gradle.kts` files that uses it, the first attempt works (build succeeds), while the second attempt fails with the same error (as it seems that the `pluginManagement.plugins {}` block only works with the `plugins {}` block).

Furthermore, there's still the fact that, if we use a shared script plugin (instead of the included build), then we lose the ability to utilize the versions TOML file, as the `libs` variable isn't available in any `settings` context, as I mentioned in, https://github.com/gmazzo/gradle-buildconfig-plugin/pull/60#discussion_r1237097173

If we really want to use a shared script plugin, then we have to extract the version somehow from the TOML file, perhaps by parsing it, which seems to be more complicated than my current setup of using an included build.

**Comment by gmazzo** [comment]
Quoting https://github.com/gmazzo/gradle-buildconfig-plugin/pull/60#issuecomment-1819494284, it's fare to assume this project requires an installed `JDK11` to build, and because the extra complexity needed to address this (included build + required settings `foojay` plugin), is just not worth it.
