### ISSUE TITLE
Add more Groovy examples

### ISSUE THREAD

**Issue by tschuchortdev** [gmazzo/gradle-buildconfig-plugin#6]
Can you add more Groovy examples next to the KotlinScript examples? My Groovy is not good enough to translate them myself unfortunately. I'm trying to use 
```Kotlin
 useKotlinOutput { internalVisibility = true } 
```
with Groovy but can not get it to work.

It would also be nice to be able to set the visibility for a Java `BuildConfig` class.

**Comment by gmazzo** [comment]
Sorry for the late response, I'll take a look at it.

**Comment by gmazzo** [comment]
These two issues are addressed at https://github.com/gmazzo/gradle-buildconfig-plugin/pull/13

**Comment by gmazzo** [comment]
Published as `3.0.0`
