### ISSUE TITLE
will it support with productFlavors ?

### ISSUE THREAD

**Issue by Egi10** [gmazzo/gradle-buildconfig-plugin#68]
Like on Android : https://developer.android.com/build/build-variants#product-flavors

**Comment by gmazzo** [comment]
Hi @Egi10 , can you elaborate a use case for this? This plugin was never meant to be a replacement of [Android's `buildConfigField`](https://developer.android.com/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code) which is already flavor-awre.

This plugin was meant to port this feature back to any Kotlin (mainly non-Android) project.

**Comment by Egi10** [comment]
I have a case where I need several configurations, such as staging, UAT, and production. Each configuration has a different base URL, and in Android, I usually use Product Flavors.

Example :
```
productFlavors {
        create("staging") {
            buildConfigField "String", "BASE_URL", "\"https://api.uat.example.com/\"" // Define specific base URL for UAT
        }
        create("prod") {
            buildConfigField "String", "BASE_URL", "\"https://api.example.com/\"" // Define specific base URL for production
        }
    }
```

For now, in KMM, I'm using the [BuildKonfig](https://github.com/yshrsmz/BuildKonfig#product-flavor) library to manage this.

**Comment by gmazzo** [comment]
This plugin works from `SourceSet` based approach. By default, applying the `java` or `kotlin` plugin, it binds to the JVM source sets, and creates an ad-hoc `BuildConfigSourceSet` per each.

Android Flavors (variants actually: buildType-flavors) are built upon `SourceSets` as well.

If what you want is to mimic Android's `BuildConfig` (having all fields from default, buildType and flavors merged into a single class), you should add something like this to the DSL:
```kotlin
    // mimics the variant-aware buildConfigField behavior from Android, by declaring fields on the final variant sourceSet
    applicationVariants.all variant@ { // per each variant (buildType-flavor)
        buildConfig.sourceSets.named(this@variant.name) { // access the sources for the variant. i.e.: `debugFoo`
            className.set("BuildConfig") // forces the class name to be the same on all, as defaults to `DebugFooBuildConfig`

            // static constants, what would you have in the `defaultConfig` on Android DSL
            buildConfigField("String", "APP_NAME", "\"${project.name}\"")
            buildConfigField("String", "APP_SECRET", "\"Z3JhZGxlLWphdmEtYnVpbGRjb25maWctcGx1Z2lu\"")
            buildConfigField("long", "BUILD_TIME", "${System.currentTimeMillis()}L")
            buildConfigField("boolean", "FEATURE_ENABLED", "${true}")
            buildConfigField("kotlin.IntArray", "MAGIC_NUMBERS", "intArrayOf(1, 2, 3, 4)")

            // and declares "flavored" constants
            buildConfigField("boolean", "IS_DEBUG", "${this@variant.buildType.isDebuggable}") 
            buildConfigField("String", "BRAND", "\"${this@variant.productFlavors.single().name}\"")
        }
    }
```
https://github.com/gmazzo/gradle-buildconfig-plugin/blob/main/demo-project/kts-android/build.gradle.kts

**Comment by rajagopalannairr** [comment]
@gmazzo - Is it possible to do the same in compose multiplatform projects.? 
In my app also I have UAT and Prod Configs How I can handle this? 

Could you please help?

**Comment by gmazzo** [comment]
Can you elaborate yours needs? May be a sample project would help to understand.

Basically, this project supports kotlin multiplatform, as you can register a `BuildConfig` class per source set.

What is not supported is generating `expect/actual` definitions, but may still create a class on each final target: `jvmMain`, `iosMain` etc

**Comment by rajagopalannairr** [comment]
Hi @gmazzo 

I am trying to create two build configurations: one for UAT and the other for PROD. I would like to keep the following information:

1. Base URL
2. App Identifier
3. Application Name
4. API keys, etc.

Could you please let me know how I can have this for two build configurations/build flavors? What is the recommended method?

**Comment by gmazzo** [comment]
Is it an Android project, a multiplatform one, it both? What are your target platforms?

I'd create for each platform leaf source set, and add the constants the.

**Comment by rajagopalannairr** [comment]
Both iOS and Android (But i am using compose multiplatform).

**Comment by gmazzo** [comment]
It's doable, but I can't write that piece of course for you sorry. 

If you understand the basics of Kotlin Multiplatform and it's source sets, it will be easy to do
