### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ZacSweers** [gmazzo/gradle-buildconfig-plugin#8]
I'm looking to adopt this plugin and contribute some (Gradle API usage) modernization if you're open to it, but I can't tell if it's still maintained as the other open issues have no response to them. If you're open to some PRs to modernize the Gradle usage (lazy task configuration, property APIs, etc), let me know 🙇‍♂️

**Comment by ZacSweers** [comment]
Here is a branch of my changes in my fork with the above mentioned updates: https://github.com/gmazzo/gradle-buildconfig-plugin/compare/master...ZacSweers:z/updateApis?expand=1

Namely:
* Use lazy task configuration (resolves #7)
* Try to use more idiomatic modern gradle Property and input APIs
* Raise min gradle version to 5.6 (I feel pretty strongly that 6.0 should be the min)
* Try to remove non-inputs from the public API. This will help with eventual configuration caching support, but not sure the work I've got there alone is enough.

**Comment by gmazzo** [comment]
Thanks for the feedback. I'll try to give a refresh to this project, mostly to migrate to `Kotlin 1.4`. Any contribution will be very welcome

**Comment by ZacSweers** [comment]
I'll PR what I have!

**Comment by gmazzo** [comment]
I've fixed major issues on version `2.1.0`. Migrating to Properties API like that will be a breaking change.

I'll work on this, probably to release it as `3.0.0`.

**Comment by gmazzo** [comment]
> I'll PR what I have!

Take a look at this https://github.com/gmazzo/gradle-buildconfig-plugin/pull/13 first, feel free to comment. I think I've covered the basis right?
