### ISSUE TITLE
Why the ctor?

### ISSUE THREAD

**Issue by Desoroxxx** [gmazzo/gradle-buildconfig-plugin#80]
I am using the plugin with Groovy and Java, and the generated class has a private ctor, my question is why not remove the ctor?

**Comment by Desoroxxx** [comment]
Abuse of language sorry it should be clearer what I meant

**Comment by TWiStErRob** [comment]
https://github.com/gmazzo/gradle-buildconfig-plugin/blob/d2d65f46922ddb8e8d3353e0cfa2b82529f19a01/demo-project/generic/build.gradle.kts#L27-L38

This is standard practice in the Java world. If a class only has static fields, then the class is meaningless when instantiated. These are called "utility classes". Checkstyle even has a rule to enforce hidden ctor: https://checkstyle.sourceforge.io/checks/design/hideutilityclassconstructor.html

Another real world example from a well-known library:
https://github.com/apache/commons-collections/blob/ac05d8fdbe62bbfe051e3b502e5f0fcfbba56c9b/src/main/java/org/apache/commons/collections4/ComparatorUtils.java#L47-L50

**Comment by TWiStErRob** [comment]
Note: if one deletes a private constructor, Java automagically generates a public zero-args constructor, see first sentence at Java specification: https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.8.9

**Comment by Desoroxxx** [comment]
Oh that makes sense I never thought about it this way, thanks
