### ISSUE TITLE
Cleaner way to add import

### ISSUE THREAD

**Issue by Desoroxxx** [gmazzo/gradle-buildconfig-plugin#81]
Currently I need to do:
`buildConfigField("org.apache.logging.log4j.LogManager", "DO_NOT_USE", "null")`
To get something to import which is fairly ugly in the generated class.

I could not do this via:
`buildConfigField("org.apache.logging.log4j.Logger", "LOGGER", "org.apache.logging.log4j.LogManager.getLogger(NAME)")`
But in my opinion this would be uglier.

Loving this plugin so far hope this could become a thing

**Comment by gmazzo** [comment]
Hi @Desoroxxx, can you elaborate a bit more this? Why are you using this plugin to generate a `LOGGER` constant? won't be just straight forward to write it your self in source code?

This plugin is mean mostly as a port of Android's `buildConfig` feature, and/or to propagate data from the build script into the final code (like the app version)

**Comment by Desoroxxx** [comment]
> Hi @Desoroxxx, can you elaborate a bit more this? Why are you using this plugin to generate a `LOGGER` constant? won't be just straight forward to write it your self in source code?
> 
> This plugin is mean mostly as a port of Android's `buildConfig` feature, and/or to propagate data from the build script into the final code (like the app version)

I used this to replace the feature of another plugin that replaced the fields in a class directly and in said class there was all my general project wide constants which aren't a lot, and so I reproduced the same behavior with this plugin, I understand if this is out of scope for this project, but I think it could still be a nice addition

**Comment by gmazzo** [comment]
Closing this for now, as I don't picture this is going to happen as it's documented right now. Feel free to comment further in the future
